# Generated by Django 5.0.6 on 2024-07-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='full_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='items',
            field=models.JSONField(default=dict),
        ),
    ]
